USE [BookingCinemaTicketsOnline]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[userName] [varchar](200) NOT NULL,
	[password] [varchar](200) NOT NULL,
	[fullName] [nvarchar](200) NULL,
	[googleID] [varchar](200) NULL,
	[googleName] [varchar](200) NULL,
	[email] [varchar](200) NULL,
	[phoneNumber] [varchar](200) NULL,
	[gender] [nvarchar](200) NULL,
	[role] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[userName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_userName] UNIQUE NONCLUSTERED 
(
	[userName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKING]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKING](
	[bookingID] [varchar](200) NOT NULL,
	[numberOfBooking] [int] NULL,
	[priceTotal] [money] NULL,
	[bookingDate] [date] NULL,
	[userName] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[bookingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CINEMA]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CINEMA](
	[cinemaID] [int] IDENTITY(1,1) NOT NULL,
	[cinemaName] [nvarchar](200) NULL,
	[city] [nvarchar](200) NULL,
	[address] [nvarchar](200) NULL,
	[hotline] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[cinemaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBERSHIP]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBERSHIP](
	[memberID] [uniqueidentifier] NOT NULL,
	[totalSpend] [money] NULL,
	[discount] [int] NULL,
	[userName] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[memberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_userName3] UNIQUE NONCLUSTERED 
(
	[userName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MOVIE]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOVIE](
	[movieID] [int] IDENTITY(1,1) NOT NULL,
	[movieName] [nvarchar](200) NULL,
	[movieContent] [nvarchar](200) NULL,
	[actor] [nvarchar](200) NULL,
	[director] [nvarchar](200) NULL,
	[age] [int] NULL,
	[movieImage] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[movieID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_movieName] UNIQUE NONCLUSTERED 
(
	[movieName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[id] [decimal](19, 2) NOT NULL,
	[amount] [int] NULL,
	[orderInfo] [nvarchar](250) NULL,
	[responseCode] [char](5) NULL,
	[transactionNo] [int] NULL,
	[bank] [char](5) NULL,
	[payDate] [date] NULL,
	[transactionStatus] [char](5) NULL,
	[bookingID] [varchar](200) NULL,
	[userName] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROOM]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROOM](
	[roomID] [int] IDENTITY(1,1) NOT NULL,
	[numberOfSeats] [int] NULL,
	[cinemaID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[roomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEATDETAILS]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEATDETAILS](
	[seatID] [varchar](3) NOT NULL,
	[seatStatus] [bit] NULL,
	[roomID] [int] NULL,
	[showtimeID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[seatID] ASC,
	[showtimeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SHOWTIME]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHOWTIME](
	[showTimeID] [int] IDENTITY(1,1) NOT NULL,
	[openDate] [date] NULL,
	[closeDate] [date] NULL,
	[hourStart] [time](7) NULL,
	[hourEnd] [time](7) NULL,
	[showStatus] [bit] NULL,
	[roomID] [int] NULL,
	[movieID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[showTimeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TICKET]    Script Date: 3/18/2024 7:55:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TICKET](
	[ticketID] [int] IDENTITY(1,1) NOT NULL,
	[showTimeID] [int] NULL,
	[seatID] [varchar](3) NULL,
	[bookingID] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ticketID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOOKING] ADD  DEFAULT (newid()) FOR [bookingID]
GO
ALTER TABLE [dbo].[MEMBERSHIP] ADD  DEFAULT (newid()) FOR [memberID]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_userName1] FOREIGN KEY([userName])
REFERENCES [dbo].[ACCOUNT] ([userName])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_userName1]
GO
ALTER TABLE [dbo].[MEMBERSHIP]  WITH CHECK ADD  CONSTRAINT [FK_user1] FOREIGN KEY([userName])
REFERENCES [dbo].[ACCOUNT] ([userName])
GO
ALTER TABLE [dbo].[MEMBERSHIP] CHECK CONSTRAINT [FK_user1]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_bookingID2] FOREIGN KEY([bookingID])
REFERENCES [dbo].[BOOKING] ([bookingID])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_bookingID2]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_userName4] FOREIGN KEY([userName])
REFERENCES [dbo].[ACCOUNT] ([userName])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_userName4]
GO
ALTER TABLE [dbo].[ROOM]  WITH CHECK ADD  CONSTRAINT [FK_cinemaID1] FOREIGN KEY([cinemaID])
REFERENCES [dbo].[CINEMA] ([cinemaID])
GO
ALTER TABLE [dbo].[ROOM] CHECK CONSTRAINT [FK_cinemaID1]
GO
ALTER TABLE [dbo].[SEATDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_roomID3] FOREIGN KEY([roomID])
REFERENCES [dbo].[ROOM] ([roomID])
GO
ALTER TABLE [dbo].[SEATDETAILS] CHECK CONSTRAINT [FK_roomID3]
GO
ALTER TABLE [dbo].[SEATDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_showTimeID2] FOREIGN KEY([showtimeID])
REFERENCES [dbo].[SHOWTIME] ([showTimeID])
GO
ALTER TABLE [dbo].[SEATDETAILS] CHECK CONSTRAINT [FK_showTimeID2]
GO
ALTER TABLE [dbo].[SHOWTIME]  WITH CHECK ADD  CONSTRAINT [FK_MovieID1] FOREIGN KEY([movieID])
REFERENCES [dbo].[MOVIE] ([movieID])
GO
ALTER TABLE [dbo].[SHOWTIME] CHECK CONSTRAINT [FK_MovieID1]
GO
ALTER TABLE [dbo].[SHOWTIME]  WITH CHECK ADD  CONSTRAINT [FK_roomID1] FOREIGN KEY([roomID])
REFERENCES [dbo].[ROOM] ([roomID])
GO
ALTER TABLE [dbo].[SHOWTIME] CHECK CONSTRAINT [FK_roomID1]
GO
ALTER TABLE [dbo].[TICKET]  WITH CHECK ADD  CONSTRAINT [FK_bookingID1] FOREIGN KEY([bookingID])
REFERENCES [dbo].[BOOKING] ([bookingID])
GO
ALTER TABLE [dbo].[TICKET] CHECK CONSTRAINT [FK_bookingID1]
GO
ALTER TABLE [dbo].[TICKET]  WITH CHECK ADD  CONSTRAINT [FK_seatID_showtimeID] FOREIGN KEY([seatID], [showTimeID])
REFERENCES [dbo].[SEATDETAILS] ([seatID], [showtimeID])
GO
ALTER TABLE [dbo].[TICKET] CHECK CONSTRAINT [FK_seatID_showtimeID]
GO
ALTER TABLE [dbo].[TICKET]  WITH CHECK ADD  CONSTRAINT [FK_showTimeID1] FOREIGN KEY([showTimeID])
REFERENCES [dbo].[SHOWTIME] ([showTimeID])
GO
ALTER TABLE [dbo].[TICKET] CHECK CONSTRAINT [FK_showTimeID1]
GO
